import { check, index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const foundationOutboxMessages = pgTable('foundation_outbox_messages', {
  id: uuid('id').primaryKey(),
  eventId: text('event_id').notNull(),
  eventVersion: integer('event_version').notNull(),
  dedupeKey: text('dedupe_key').notNull(),
  recipientAccountId: uuid('recipient_account_id').notNull(),
  payloadAlgorithm: text('payload_algorithm').notNull(),
  payloadKeyVersion: text('payload_key_version').notNull(),
  payloadIvBase64: text('payload_iv_base64').notNull(),
  payloadCiphertextBase64: text('payload_ciphertext_base64').notNull(),
  payloadAuthTagBase64: text('payload_auth_tag_base64').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull(),
  availableAt: timestamp('available_at', { withTimezone: true, mode: 'date' }).notNull(),
  attemptCount: integer('attempt_count').notNull().default(0),
  status: text('status').notNull(),
  leaseToken: uuid('lease_token'),
  leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true, mode: 'date' }),
  lastErrorCode: text('last_error_code'),
  deliveredAt: timestamp('delivered_at', { withTimezone: true, mode: 'date' }),
}, (table) => [
  uniqueIndex('foundation_outbox_dedupe_key_idx').on(table.dedupeKey),
  check('foundation_outbox_event_version_positive', sql`${table.eventVersion} >= 1`),
  check('foundation_outbox_event_id_format', sql`${table.eventId} ~ '^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$'`),
  check('foundation_outbox_dedupe_bounds', sql`char_length(btrim(${table.dedupeKey})) BETWEEN 1 AND 256`),
  check('foundation_outbox_payload_algorithm', sql`${table.payloadAlgorithm} = 'A256GCM'`),
  check('foundation_outbox_payload_key_version', sql`${table.payloadKeyVersion} = 'v1'`),
  check('foundation_outbox_payload_nonblank', sql`btrim(${table.payloadIvBase64}) <> '' AND btrim(${table.payloadCiphertextBase64}) <> '' AND btrim(${table.payloadAuthTagBase64}) <> ''`),
  check('foundation_outbox_attempt_nonnegative', sql`${table.attemptCount} >= 0`),
  check('foundation_outbox_status', sql`${table.status} IN ('PENDING','PROCESSING','DELIVERED','DEAD')`),
  check('foundation_outbox_error_code_format', sql`${table.lastErrorCode} IS NULL OR ${table.lastErrorCode} ~ '^[a-z][a-z0-9-]{0,63}$'`),
  check('foundation_outbox_time_order', sql`${table.availableAt} >= ${table.createdAt}`),
  check('foundation_outbox_lease_state', sql`(${table.status} = 'PROCESSING' AND ${table.leaseToken} IS NOT NULL AND ${table.leaseExpiresAt} IS NOT NULL) OR (${table.status} <> 'PROCESSING' AND ${table.leaseToken} IS NULL AND ${table.leaseExpiresAt} IS NULL)`),
  check('foundation_outbox_delivery_state', sql`(${table.status} = 'DELIVERED' AND ${table.deliveredAt} IS NOT NULL) OR (${table.status} <> 'DELIVERED' AND ${table.deliveredAt} IS NULL)`),
  index('foundation_outbox_claim_idx').on(table.availableAt, table.createdAt, table.id).where(sql`${table.status} IN ('PENDING','PROCESSING')`),
  index('foundation_outbox_recipient_idx').on(table.recipientAccountId, table.createdAt),
]);
