import type { TaymexLocale } from './locales';
export interface AppMessages {
  products:string; administration:string; platformReady:string; skip:string; navigation:string; mobileNavigation:string; open:string; close:string; collapse:string; expand:string;
  foundationUi:string; publicIntro:string; productsIntro:string; foundationIntro:string; openSection:string;
}
export const messages: Record<TaymexLocale, AppMessages> = {
  ar: {products:'المنتجات',administration:'الإدارة',platformReady:'جاهز لبدء الشريحة العمودية للمنتجات',skip:'انتقل إلى المحتوى',navigation:'التنقل الرئيسي',mobileNavigation:'التنقل على الهاتف',open:'فتح القائمة',close:'إغلاق القائمة',collapse:'طي القائمة',expand:'توسيع القائمة',foundationUi:'أساس الواجهة',publicIntro:'بوابة متعددة اللغات مبنية على نظام واجهة واحد ومحكوم.',productsIntro:'مسار الإدارة الحالي للمنتجات.',foundationIntro:'مرجع حي للمكونات والحالات والاستجابة وإمكانية الوصول.',openSection:'فتح القسم'},
  tr: {products:'Ürünler',administration:'Yönetim',platformReady:'Ürünler dikey dilimine başlamaya hazır',skip:'İçeriğe geç',navigation:'Ana gezinme',mobileNavigation:'Mobil gezinme',open:'Menüyü aç',close:'Menüyü kapat',collapse:'Menüyü daralt',expand:'Menüyü genişlet',foundationUi:'Arayüz temeli',publicIntro:'Tek ve yönetilen arayüz sistemi üzerine kurulu çok dilli giriş.',productsIntro:'Mevcut ürün yönetimi yolu.',foundationIntro:'Bileşenler, durumlar, duyarlılık ve erişilebilirlik için canlı referans.',openSection:'Bölümü aç'},
  en: {products:'Products',administration:'Administration',platformReady:'Ready to begin the Products vertical slice',skip:'Skip to content',navigation:'Primary navigation',mobileNavigation:'Mobile navigation',open:'Open navigation',close:'Close navigation',collapse:'Collapse navigation',expand:'Expand navigation',foundationUi:'UI foundation',publicIntro:'A multilingual entry surface built on one governed interface system.',productsIntro:'The current Products administration route.',foundationIntro:'A live reference for components, states, responsiveness and accessibility.',openSection:'Open section'}
};
